### ISSUE TITLE
node v0.12.2 error

### ISSUE THREAD

**Issue by Kruemmelmonster** [InstantWebP2P/peer-vnc#10]
Hello,

i cant seem to get it working with the current version of node.js

i installed it as followed:

mkdir -p testapp/node_modules
cd testapp/node_modules
git clone https://github.com/InstantWebP2P/peer-vnc && cd peer-vnc
npm install httpp-binary
nom install 
cd ~/testapp

then made a new js file and copied the example proxy in 
var Proxy = require('peer-vnc');

new Proxy('192.168.1.1:5900', function(err, proxyURL){
    console.log('VNC                   Proxy URL(please open it on browser)');
    for (var k in proxyURL) {
        console.log(k+'        '+proxyURL[k]);
    }
});

after that i tried to node testVNC.js and got the error message that httpp is missing wich i manually installed in the peer-vnc directory and in the testapp directory.

It would be great if i get a reply telling me what i did wrong!

Thanks in advance,
Kru~

**Comment by sequoiar** [comment]
@Kruemmelmonster  peer-vnc depends on node-httpp(fork of node.js), I will update peer-vnc  package

**Comment by Kruemmelmonster** [comment]
just for a heads up is there a ETA when this is gonna happen?
:+1:
