### ISSUE TITLE
Unable to Access OSX Yosemite 

### ISSUE THREAD

**Issue by manju4ever** [InstantWebP2P/peer-vnc#11]
I tried to access OSx - Yosemite by running peer-vnc, but i'm getting the following error
![image](https://cloud.githubusercontent.com/assets/9355984/12206296/1f337160-b666-11e5-8a8a-7d65417fe6fe.png)

**Comment by sequoiar** [comment]
@manju4ever Is the issue still there ? I didn't see it.
