### ISSUE TITLE
On MacOS:  lazy symbol binding failed

### ISSUE THREAD

**Issue by larytet** [InstantWebP2P/peer-vnc#13]
Hi,

I attempt to start the peer-vnc on Mac. This is what I get 

```
./bin/osx/node ./bin/peer-vnc -t localhost:5901                                                                                                                                                          

dyld: lazy symbol binding failed: Symbol not found: __ZN2v811HandleScopeC1Ev
  Referenced from: /Users/ddd/Downloads/peer-vnc-pkg-release-osx/node_modules/wspp/node_modules/utf-8-validate/build/Release/validation.node
  Expected in: dynamic lookup

dyld: Symbol not found: __ZN2v811HandleScopeC1Ev
  Referenced from: /Users/ddd/Downloads/peer-vnc-pkg-release-osx/node_modules/wspp/node_modules/utf-8-validate/build/Release/validation.node
  Expected in: dynamic lookup

[1]    5740 trace trap  ./bin/osx/node ./bin/peer-vnc -t localhost:5901
```

What am I missing?
Thanks.

**Comment by sequoiar** [comment]
@larytet what's your version of OSX ?

**Comment by larytet** [comment]
10.10.5 (14F1912)
I have tried to run in Windows 8 64 bits following the instructions in the windows-howto.md
This is the output 

`C:\Users\ddd\Downloads\peer-vnc-pkg-release-windows\peer-vnc-pkg-release-windows>.\bin\node.exe .\bin\peer-vnc -t loc
alhost:5900 -k anywords

module.js:340
    throw err;
          ^
Error: Cannot find module 'http-auth'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (C:\Users\ddd\Downloads\peer-vnc-pkg-release-windows\peer-vnc-pkg-release-windows\novnc.js:
11:16)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)

C:\Users\ddd\Downloads\peer-vnc-pkg-release-windows\peer-vnc-pkg-release-windows>
`

**Comment by larytet** [comment]
I have tried to create vnc-example.js file as specified in the README. This approach failed too in Windows.

**Comment by sequoiar** [comment]
@larytet just fix dylib issue on OSX , please use package
 https://github.com/InstantWebP2P/peer-vnc/archive/pkg-release-osx.zip

on windows, please run npm install http-auth first and try again

**Comment by larytet** [comment]
Thanks
