### ISSUE TITLE
peer-vnc runs, but unable to connect to the resulting URL

### ISSUE THREAD

**Issue by dhsc19** [InstantWebP2P/peer-vnc#6]
I am able to run peer-vnc and I am getting something like this:

iWebPP.io connect ready
VNC                            Proxy URL(please open it on browser)
localhost:5901        https://08a5fc8425f8177e33948af8787bb4dc.vurl.iwebpp.com:51688/vtoken/65086aee6eedac21/localhost-5901

When I go to the https link, I'm getting "web page not found" (a browser message).  It doesn't look like the Internet host is up.

**Comment by dhsc19** [comment]
Sorry, I was incomplete in my info.  I'm having the problem with the RPi package.  It appears that I am able to establish connection to a web service of some sort, but now I am getting this message:

An error has occurred: {"code":"ECONNRESET"}

**Comment by dhsc19** [comment]
I seem to have been able to fix this by running "npm install" in the /peer-vnc-pkg-release-rpi directory

**Comment by sequoiar** [comment]
@dhsc19 good catch. I will update RPI release package
