### ISSUE TITLE
offerSdp timeout

### ISSUE THREAD

**Issue by Thomas-S-Pi** [InstantWebP2P/peer-vnc#8]
I get the following error when using the Raspberry Pi 2 with this (usually excellent!) software:
offerSdp timeout,setup SDP session failed
(!!!DDOS attack, ctrlpkt MAC check failed.pkt.type:2)
name-client create failed:"offerSdp timeout,setup SDP session failed"

**Comment by sequoiar** [comment]
@Thomas-S-Pi 
please try do "npm install" in peer-vnc directory, it will install latest peer-vnc codes.

**Comment by Thomas-S-Pi** [comment]
When I do this I get several errors starting with npm ERR! Error: No compatible version found: qrcode-terminal@'^0.9.5' . I tried deleting the peer-vnc folder and reinstalling with npm install peer-vnc. That worked BUT i still get the same error when I run peer-vnc:

offerSdp timeout,setup SDP session failed
name-client create failed:"offerSdp timeout,setup SDP session failed"
VNC                            Proxy URL(please open it on browser)

**Comment by sequoiar** [comment]
@Thomas-S-Pi 
Please try to remove qrcode-terminal from package.json in peer-vnc directory, and try npm install again

**Comment by Thomas-S-Pi** [comment]
I’ve done that now. Npm install works but I still get the same error when I run peer-vnc. When I did npm install, only two lines were outputted:

npm http GET https://registry.npmjs.org/iwebpp.io

npm http 304 https://registry.npmjs.org/iwebpp.io
